# Generated by Django 4.0.5 on 2022-07-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_timestemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catagories',
            field=models.CharField(choices=[('wearable', 'Wearable'), ('digital', 'Digital')], default='wearable', max_length=255),
        ),
    ]
